# Copyright (c) 2024, Fonden Mærsk Mc-Kinney Møller Center for Zero Carbon Shipping
#
# This file is part of NavigaTE.
#
# NavigaTE is a free software: you can modify it under the
# terms of the full license agreement found in the LICENSE
# file located in the root directory of this source tree.
#
# Description: Cost of capital for financing a vessel, also used as the discount rate.
# Unit: Fraction / year

Variable "cost_of_capital_vessel" {
	Value = 0.07
}
