Surface "speed_draft_power_surface_tanker_300k_dwt" {
	Table [		 
					 0.0		1.0
			 9		 5.0		6.9		# extrapolated manually
			10		 5.5		8.0
			11		 6.5		9.4
			12		 8.0	   11.6
			13		 9.9	   14.3
			14		12.3	   17.8
			15		15.2	   21.9
			16		18.8	  999.0		# 999.0 is undefined - leads to engine power constraint failure
			17		23.1	  999.0		# 999.0 is undefined - leads to engine power constraint failure

	]
}